### ISSUE TITLE
brew installation warnings after 'brew tap qatools/formulas'

### ISSUE THREAD

**Issue by m3nthal** [allure-framework/homebrew-allure#2]
Warnings after `brew tap qatools/formulas`:

> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:8:in `<class:AllureCommandline>'
> Please report this to the qatools/formulas tap!
> 
> Warning: Calling SoftwareSpec#sha1 is deprecated!
> Use SoftwareSpec#sha256 instead.
> /usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:8:in `<class:AllureCommandline>'
> Please report this to the qatools/formulas tap!
> 
> Warning: Calling Resource#sha1 is deprecated!
> Use Resource#sha256 instead.
> /usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:8:in `<class:AllureCommandline>'
> Please report this to the qatools/formulas tap!

**Comment by m3nthal** [comment]
Additional warnings after `brew install allure-commandline`:

> ==> Installing allure-commandline from qatools/formulas
> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:8:in `<class:AllureCommandline>'
> Please report this to the qatools/formulas tap!
> 
> Warning: Calling SoftwareSpec#sha1 is deprecated!
> Use SoftwareSpec#sha256 instead.
> /usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:8:in `<class:AllureCommandline>'
> Please report this to the qatools/formulas tap!
> 
> Warning: Calling Resource#sha1 is deprecated!
> Use Resource#sha256 instead.
> /usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:8:in `<class:AllureCommandline>'
> Please report this to the qatools/formulas tap!
> 
> ==> Downloading https://github.com/allure-framework/allure-core/releases/download/allure-core-1.4.23
> ==> Downloading from https://github-cloud.s3.amazonaws.com/releases/14718267/e0820d70-ed22-11e5-89ae
> ######################################################################## 100.0%
> Warning: Calling Pathname#sha1 is deprecated!
> Use Pathname#sha256 instead.
> /usr/local/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

**Comment by vania-pooh** [comment]
Fixed in https://github.com/qatools/homebrew-formulas/commit/af7b8e45b88aa3f9813c7f1458137549a07c2a7d
